name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Nuke restore + build + publish
        run: ./build.sh --configuration Release -target compile+publish
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: scatterbrained-dev-blog
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: './artifacts/blog.Api'
